package com.syeedode.datastructures;/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;

public class DataStructureApplicationTest {
    @Test public void testSomeLibraryMethod() {
    }
}
